### ISSUE TITLE
Trackobot tracking failing

### ISSUE THREAD

**Issue by ThaWeatherman** [HearthSim/arcane_tracker#37]
Unsure if this is related to the updates to trackobot that happened yesterday, but now uploading always fails because of a "network error". I am also unable to open my TB profile using the button in Settings. [Others are experiencing it as well](https://www.reddit.com/r/arcanetracker/comments/5lw7zs/trackobot_uploads_failing/).

**Comment by mandaleFR** [comment]
I have exactly the same issue with the game since Track-O-Bot updated the website.

**Comment by Shockii412** [comment]
Same Thing is happening for me as well. Good to know Im not the only one

**Comment by martinbonnin** [comment]
Should be fixed with 2.04. Let me know how that goes.

**Comment by mandaleFR** [comment]
Hi,

It's only fixed for the upload of a game's result.

The bug is still there for the opening of the profile using the browser.

**Comment by martinbonnin** [comment]
indeed, sorry about that, will make a new release asap

**Comment by ThaWeatherman** [comment]
@martinbonnin if you want to associate commits with issues: http://stackoverflow.com/a/6742691

**Comment by bibhashthakur** [comment]
I'm still facing that problem. Track-o-bot tracking is failing.

**Comment by martinbonnin** [comment]
What version are you using ?

**Comment by bibhashthakur** [comment]
2.04

**Comment by martinbonnin** [comment]
Please try the 2.05 beta: https://play.google.com/apps/testing/net.mbonnin.arcanetracker.
If that still fails, send me the exact message displayed when the upload fails and then go to setting -> send feedback to send a detailed log. Thanks !

**Comment by mmascher** [comment]
Should close this, works now
